# Generated by Django 6.0.4 on 2026-05-04 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('csv', 'CSV (табличный)'), ('pdf', 'PDF (печатный)')], max_length=10, verbose_name='Тип отчёта')),
                ('filters_applied', models.JSONField(blank=True, default=dict, null=True, verbose_name='Применённые фильтры')),
                ('records_count', models.PositiveIntegerField(default=0, verbose_name='Количество записей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата формирования')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись экспорта',
                'verbose_name_plural': 'Журнал экспорта',
                'ordering': ['-created_at'],
            },
        ),
    ]
