# Generated by Django 6.0.4 on 2026-05-04 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Регистрационный номер')),
                ('title', models.CharField(max_length=200, verbose_name='Тема обращения')),
                ('description', models.TextField(verbose_name='Текст обращения')),
                ('category', models.CharField(choices=[('social', 'Социальная поддержка'), ('pension', 'Пенсионные вопросы'), ('housing', 'Жилищные вопросы'), ('other', 'Иное')], default='other', max_length=50, verbose_name='Категория')),
                ('contact_email', models.EmailField(db_index=True, max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=18, verbose_name='Контактный телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок рассмотрения')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Гибкое хранение специфичных параметров', null=True, verbose_name='Дополнительные метаданные')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
                'permissions': [('can_reassign', 'Может переназначать обращения'), ('can_export_data', 'Может экспортировать данные')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('STATUS_CHANGE', 'Смена статуса'), ('DELETE', 'Удаление'), ('LOGIN', 'Вход в систему'), ('EXPORT', 'Экспорт данных')], max_length=20, verbose_name='Тип действия')),
                ('target_model', models.CharField(max_length=50, verbose_name='Сущность')),
                ('target_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('details', models.TextField(blank=True, verbose_name='Описание действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
            ],
            options={
                'verbose_name': 'Запись журнала аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='appeals/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png', 'zip'])], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Код статуса')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('color', models.CharField(default='secondary', max_length=20, verbose_name='Цвет (CSS класс)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['order'],
            },
        ),
    ]
